name: Run Ticket Script

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 替换为你的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: cd ticket && python get_issue_values2.py

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ticket-data
        path: ticket/data/issue_values.json